var input = require('fs').readFileSync('/dev/stdin').toString().trim().split('\n');
var x = input[0].split(' ').map(function(e) { return parseInt(e); });
var h = x[0], m = x[1], s = x[2];
s += parseInt(input[1]);
m += Math.floor(s / 60);
s %= 60;
h += Math.floor(m / 60);
m %= 60;
h %= 24;
console.log(h + ' ' + m + ' ' + s);
